#!/usr/bin/env bash
# PreToolUse (Edit|Write|MultiEdit): refuse edits that break project rules before they happen.
#  - committed migration files are immutable (create a new migration instead)
#  - src/generated/ is Prisma output (change prisma/schema.prisma and run pnpm db:generate)
set -euo pipefail
cd "${CLAUDE_PROJECT_DIR:-.}"

FILE="$(jq -r '.tool_input.file_path // empty')"
[ -z "$FILE" ] && exit 0
REL="$(realpath -m --relative-to="$(pwd)" "$FILE" 2>/dev/null || echo "$FILE")"

case "$REL" in
  prisma/migrations/*/migration.sql)
    if git cat-file -e "HEAD:$REL" 2>/dev/null; then
      echo "Blocked: $REL is already committed. Applied migrations must never change — edit prisma/schema.prisma and create a NEW migration (pnpm db:migrate, or pnpm db:migrate:wasm create <name>)." >&2
      exit 2
    fi
    ;;
  src/generated/*)
    echo "Blocked: $REL is generated by Prisma. Edit prisma/schema.prisma and run pnpm db:generate." >&2
    exit 2
    ;;
esac
exit 0
