#!/usr/bin/env node
/**
 * Fallback migration runner using Prisma's WebAssembly schema engine.
 *
 * Why: the Prisma CLI downloads a native schema-engine binary from binaries.prisma.sh.
 * Some sandboxed/cloud environments block that host, which breaks `prisma migrate`.
 * This script talks to the same engine (compiled to WASM, shipped on npm) through the
 * pg driver adapter, so it produces identical SQL and writes the same `_prisma_migrations`
 * history — migrations created/applied here are fully compatible with the normal CLI.
 *
 * Usage (pnpm scripts):
 *   pnpm db:migrate:wasm create <name>   # diff git-HEAD schema → working schema into a new migration
 *   pnpm db:migrate:wasm deploy          # like `prisma migrate deploy`
 *
 * Prefer the normal `pnpm db:migrate` / `pnpm db:deploy` wherever the binary download works.
 */
import "dotenv/config";
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { SchemaEngine } from "@prisma/schema-engine-wasm";
import { PrismaPg } from "@prisma/adapter-pg";
import { bindMigrationAwareSqlAdapterFactory } from "@prisma/driver-adapter-utils";

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const SCHEMA_PATH = path.join(ROOT, "prisma", "schema.prisma");
const MIGRATIONS_DIR = path.join(ROOT, "prisma", "migrations");
const LOCKFILE = path.join(MIGRATIONS_DIR, "migration_lock.toml");
const LOCKFILE_CONTENT =
  '# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "postgresql"\n';
const FILTERS = { externalTables: [], externalEnums: [] };

function pgConfigFromUrl(raw) {
  // Pass discrete fields (not connectionString) so the adapter's shadow-database
  // override of `database` actually takes effect.
  const u = new URL(raw);
  return {
    host: u.hostname,
    port: u.port ? Number(u.port) : 5432,
    user: decodeURIComponent(u.username),
    password: decodeURIComponent(u.password),
    database: decodeURIComponent(u.pathname.replace(/^\//, "")),
  };
}

function migrationsList() {
  fs.mkdirSync(MIGRATIONS_DIR, { recursive: true });
  const dirs = fs
    .readdirSync(MIGRATIONS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
  return {
    baseDir: MIGRATIONS_DIR,
    lockfile: {
      path: "migration_lock.toml",
      content: fs.existsSync(LOCKFILE) ? fs.readFileSync(LOCKFILE, "utf8") : null,
    },
    shadowDbInitScript: "",
    migrationDirectories: dirs.map((name) => {
      const file = path.join(MIGRATIONS_DIR, name, "migration.sql");
      return {
        path: name,
        migrationFile: {
          path: "migration.sql",
          content: fs.existsSync(file)
            ? { tag: "ok", value: fs.readFileSync(file, "utf8") }
            : { tag: "error", value: `${file} not found` },
        },
      };
    }),
  };
}

function timestamp() {
  const d = new Date();
  const p = (n) => String(n).padStart(2, "0");
  return `${d.getUTCFullYear()}${p(d.getUTCMonth() + 1)}${p(d.getUTCDate())}${p(d.getUTCHours())}${p(d.getUTCMinutes())}${p(d.getUTCSeconds())}`;
}

async function main() {
  const [command, rawName] = process.argv.slice(2);
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_URL is not set");

  const schema = fs.readFileSync(SCHEMA_PATH, "utf8");
  const adapter = bindMigrationAwareSqlAdapterFactory(new PrismaPg(pgConfigFromUrl(url)));
  const engine = await SchemaEngine.new({ datamodels: [[SCHEMA_PATH, schema]] }, () => {}, adapter);

  try {
    if (command === "deploy") {
      const { appliedMigrationNames } = await engine.applyMigrations({
        migrationsList: migrationsList(),
        filters: FILTERS,
      });
      console.log(
        appliedMigrationNames.length
          ? `Applied: ${appliedMigrationNames.join(", ")}`
          : "No pending migrations.",
      );
    } else if (command === "create") {
      const name = (rawName ?? "").toLowerCase().replace(/[^a-z0-9_]+/g, "_").replace(/^_|_$/g, "");
      if (!name) throw new Error("Usage: prisma-wasm.mjs create <name>");
      // The WASM engine can't create a shadow database for Postgres, so instead of replaying
      // migrations we diff the committed schema (git HEAD) against the working-tree schema.
      // This is correct as long as HEAD's schema.prisma matches HEAD's migrations — i.e. always
      // commit schema changes together with their migration.
      const hasMigrations = migrationsList().migrationDirectories.length > 0;
      let from = { tag: "empty" };
      if (hasMigrations) {
        const ref = process.env.FROM_REF ?? "HEAD";
        const previous = execFileSync("git", ["show", `${ref}:prisma/schema.prisma`], {
          cwd: ROOT,
          encoding: "utf8",
        });
        from = { tag: "schemaDatamodel", files: [{ path: SCHEMA_PATH, content: previous }] };
      }
      const out = await engine.diff({
        from,
        to: { tag: "schemaDatamodel", files: [{ path: SCHEMA_PATH, content: schema }] },
        script: true,
        shadowDatabaseUrl: null,
        exitCode: null,
        filters: FILTERS,
      });
      const script = (out.stdout ?? "").trim();
      if (!script || script === "-- This is an empty migration.") {
        console.log("No schema changes — nothing to create.");
        return;
      }
      const dir = path.join(MIGRATIONS_DIR, `${timestamp()}_${name}`);
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, "migration.sql"), `${script}\n`);
      if (!fs.existsSync(LOCKFILE)) fs.writeFileSync(LOCKFILE, LOCKFILE_CONTENT);
      console.log(`Created ${path.relative(ROOT, dir)}/migration.sql — review it, then run: pnpm db:migrate:wasm deploy`);
    } else {
      throw new Error("Usage: prisma-wasm.mjs <deploy|create <name>>");
    }
  } finally {
    engine.free?.();
  }
}

main().catch((e) => {
  console.error(e?.message ?? e);
  process.exit(1);
});
