#!/usr/bin/env node
/**
 * Screenshot pages at phone and desktop widths, in English and Arabic, logged in as the seeded admin.
 *
 *   pnpm screenshots                                   # default routes
 *   pnpm screenshots -- --routes "/,/products" --base http://localhost:3000 --out docs/screenshots
 *
 * Needs the app running and seeded. Uses CHROMIUM_PATH if set, the cloud image's Chromium if present,
 * otherwise Playwright's own (install once with: pnpm exec playwright install chromium).
 */
import "dotenv/config";
import fs from "node:fs";
import path from "node:path";
import { chromium } from "playwright";

const DEFAULT_ROUTES = ["/login", "/"];
const VIEWPORTS = {
  mobile: { width: 375, height: 812 },
  desktop: { width: 1280, height: 800 },
};
const LOCALES = ["en", "ar"];

function arg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}

function chromiumPath() {
  if (process.env.CHROMIUM_PATH) return process.env.CHROMIUM_PATH;
  const base = "/opt/pw-browsers";
  if (!fs.existsSync(base)) return undefined;
  const dir = fs.readdirSync(base).find((d) => /^chromium-\d+$/.test(d));
  const exe = dir && path.join(base, dir, "chrome-linux", "chrome");
  return exe && fs.existsSync(exe) ? exe : undefined;
}

const slug = (route) => (route === "/" ? "home" : route.replace(/^\//, "").replace(/[^a-z0-9]+/gi, "-"));

async function login(page, base) {
  const password = process.env.SEED_ADMIN_PASSWORD;
  if (!password) throw new Error("SEED_ADMIN_PASSWORD missing from .env");
  await page.goto(`${base}/login`);
  await page.locator('input[type="email"]').fill("admin@hamoodtv.local");
  await page.locator('input[type="password"]').fill(password);
  await page.locator('button[type="submit"]').click();
  await page.waitForURL((url) => !url.pathname.startsWith("/login"), { timeout: 30_000 });
}

async function main() {
  const base = arg("base", "http://localhost:3000").replace(/\/$/, "");
  const out = path.resolve(arg("out", "docs/screenshots"));
  const routes = arg("routes", DEFAULT_ROUTES.join(","))
    .split(",")
    .map((r) => r.trim())
    .filter(Boolean);
  fs.mkdirSync(out, { recursive: true });

  const browser = await chromium.launch({ executablePath: chromiumPath() });
  const written = [];
  const problems = [];
  try {
    for (const locale of LOCALES) {
      for (const [vpName, viewport] of Object.entries(VIEWPORTS)) {
        const context = await browser.newContext({ viewport, deviceScaleFactor: vpName === "mobile" ? 2 : 1 });
        await context.addCookies([{ name: "NEXT_LOCALE", value: locale, url: base }]);
        const page = await context.newPage();
        page.on("pageerror", (e) => problems.push(`${locale}/${vpName}: page error ${e.message}`));
        let loggedIn = false;
        for (const route of routes) {
          if (route !== "/login" && !loggedIn) {
            await login(page, base);
            loggedIn = true;
          }
          await page.goto(`${base}${route}`, { waitUntil: "networkidle" });
          const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1);
          if (overflow) problems.push(`${route} ${vpName}/${locale}: horizontal scroll`);
          const dir = await page.evaluate(() => document.documentElement.dir);
          if ((locale === "ar") !== (dir === "rtl")) problems.push(`${route} ${vpName}/${locale}: dir="${dir}"`);
          const file = path.join(out, `${slug(route)}-${vpName}-${locale}.png`);
          await page.screenshot({ path: file, fullPage: true });
          written.push(path.relative(process.cwd(), file));
        }
        await context.close();
      }
    }
  } finally {
    await browser.close();
  }

  const index = [
    "# Screenshots",
    "",
    `Generated by \`pnpm screenshots\` on ${new Date().toISOString().slice(0, 10)}.`,
    "",
    ...routes.flatMap((r) => [
      `## ${r}`,
      "",
      "| | English | العربية |",
      "|---|---|---|",
      ...Object.keys(VIEWPORTS).map(
        (vp) => `| ${vp} | ![](${slug(r)}-${vp}-en.png) | ![](${slug(r)}-${vp}-ar.png) |`,
      ),
      "",
    ]),
  ].join("\n");
  fs.writeFileSync(path.join(out, "README.md"), index);

  console.log(`Wrote ${written.length} screenshots to ${path.relative(process.cwd(), out)}/`);
  if (problems.length) {
    console.log("Automatic checks found problems:");
    for (const p of problems) console.log(`  - ${p}`);
    process.exitCode = 1;
  } else {
    console.log("Automatic checks: no horizontal scroll, correct dir on every page.");
  }
}

main().catch((e) => {
  console.error(e.message ?? e);
  process.exit(1);
});
